### ISSUE TITLE
Export database

### ISSUE THREAD

**Issue by lapega** [mikelolasagasti/revelation#12]
Hello!
I have a lot of keys in Revelation, since it doesn't work under python3 I need to migrate to another key manager, anything will do.

I already tried to export in all Revelation formats, but I can't get it to work in different managers (Bitwarden, keepass).

What do you recommend? Thanks

**Comment by mikelolasagasti** [comment]
I just merged an exporter to Bitwarden in `devel` branch. If building `revelation`doesn't scare you, you can follow steps in https://github.com/mikelolasagasti/revelation/pull/11#issuecomment-669346763 to use it, otherwise I'll be releasing a new version soon.

**Comment by lapega** [comment]
Oh, excellent notice.
I'll wait for the new version, I'm very comfortable using Revelation.
Thanks!
