### ISSUE TITLE
No-longer available in Debian/Ubuntu archives.

### ISSUE THREAD

**Issue by netlore** [mikelolasagasti/revelation#19]
I'm so glad to see this tool is being developed again, I miss it already in 20.04, and have now created a convoluted container system to allow me to continue using it... but had almost given up and migrated to an alternate product.

I guess this is not an "issue" with the code, but I really hope you will be able to get this excellent tool included in the Debian/Ubuntu repo's again.  I know it's been a long time since there was a stable release, but I'm sure there are more people out there using it than you think.

**Comment by mikelolasagasti** [comment]
It seems 0.5.0 has been packaged for Debian but not available yet:

https://ftp-master.debian.org/new/revelation_0.5.0-1.html
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=968477

**Comment by z4nD4R** [comment]
Hell yeah, I'd appreciated to find it in Ubu repo as well. Missing this awesome tool already...

**Comment by HumanG33k** [comment]
Debian testing update today so it will be in the next release (if no trouble).
For stable version it always can be install manually from .deb . (Maybe you also have to install some dependancies )
I do not remember well but you may have to had a little hack to force the use of python 2 (for revelation package only support it)

**Comment by mikelolasagasti** [comment]
Package available in Debian testing and Unstable:

https://tracker.debian.org/pkg/revelation

Package available for Ubuntu Hirsute (21.04):

https://packages.ubuntu.com/hirsute/revelation

Other can be tracked in repology for example:

https://repology.org/project/revelation/versions

The only missing part. sadly, would be current Debian Stable and Ubuntu-20.04. For those manual install (not complex) or Flatpak would be the current options.

**Comment by mikelolasagasti** [comment]
Closing the issue as current Debian Stable has 0.5.4 and so does latest Ubuntu LTS.
