### ISSUE TITLE
Consistent Stack Track

### ISSUE THREAD

**Issue by mhmoran** [mikelolasagasti/revelation#21]
658 items in the store.  Divided into folders based on usage,  95% are passwords for websites, the remaining 5% are credit card info.

My entry for my Github credentials, causes the following stack trace EVERY time. It doesn't matter if I try it right after opening
revelation or if I've been using it for awhile.

Any chance, that this is related the contents of the password?    I haven't found another entry that will generate said stack trace, but once I trip the stack trace, everyone after it will generate the stack trace if I continue.

> Traceback (most recent call last):
  File "/usr/local/bin/revelation", line 774, in __cb_tree_doubleclick
    self.entry_goto((iter,))
  File "/usr/local/bin/revelation", line 1349, in entry_goto
    util.execute_child(command)
  File "/usr/local/lib/python3.8/site-packages/revelation/util.py", line 184, in execute_child
    items = shlex.split(command.encode("iso-8859-1"), 0)
  File "/usr/lib/python3.8/shlex.py", line 311, in split
    return list(lex)
  File "/usr/lib/python3.8/shlex.py", line 300, in __next__
    token = self.get_token()
  File "/usr/lib/python3.8/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.8/shlex.py", line 140, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'bytes' object has no attribute 'read'

Anything else I can provide to help ?

**Comment by gbm19** [comment]
Attached patch may solve the issue.
[issue-21.patch.txt](https://github.com/mikelolasagasti/revelation/files/5124089/issue-21.patch.txt)

**Comment by mikelolasagasti** [comment]
Thanks @gbm19 !

@mhmoran I've tested the patch and is working correctly. You can change manually the file if you require or build from master again. I'll release 0.5.1 this week with this fix.
