### ISSUE TITLE
quirk in 0.5.1

### ISSUE THREAD

**Issue by mhmoran** [mikelolasagasti/revelation#22]
In the previous python 2 version,  when using the dialog to select the file to open on startup,  there was a text widget that allowed for typing in the name.  I used that ability extensively as I name all my vault files  .name .   think  .rev_work,  .rev_personal, .rev_consulting, etc ( this allows me to keep the files  less than 1000 entries each ).

In the 0.5.1 version,  I'm not finding a way to do that.  The selection is strictly point-n-click, which does NOT show .files

Thoughts?

**Comment by gbm19** [comment]
Try 'Ctrl+L' or start typing '.name...' when the file dialog shows up.
See http://lazka.github.io/pgi-docs/Gtk-3.0/classes/FileChooserWidget.html#Gtk.FileChooserWidget.signals.location_toggle_popup

**Comment by mhmoran** [comment]
thank you .. different route to the same place.  Thanks.k
