### ISSUE TITLE
instructions for compiling from source on Ubuntu/Debian

### ISSUE THREAD

**Issue by tpapp** [mikelolasagasti/revelation#29]
Until #19 is fixed, it would be useful to have instructions on how to install on Debian/Ubuntu from sources, ideally in `$HOME` if the user prefers that (possibly running from the source dir). I still didn't get it working (cf #26), but something along the lines of
```
sudo apt install make git python-gi-dev python3-crypto python3-pwquality # is this all?
git clone https://github.com/mikelolasagasti/revelation.git revelation-src
cd revelation-src
./autogen.sh
./configure
make
```

**Comment by mikelolasagasti** [comment]
Install build requirements:

    # get required packages
    sudo apt install build-essential make gcc autoconf autopoint gettext
    sudo apt install python-is-python3 libglib2.0-dev-bin libgtk-3-dev python-gi-dev python3-cryptodome python3-pwquality

If git master wants to be installed:
 
    # ensure git is installed
    sudo apt install git
	
    # get source from git repo
    mkdir ~/build
    cd ~/build
    git clone https://github.com/mikelolasagasti/revelation.git
    cd revelation
	./autogen.sh

If tarball is used:

    # download tarball
	wget https://github.com/mikelolasagasti/revelation/releases/download/revelation-0.5.3/revelation-0.5.3.tar.xz
	tar xf revelation-0.5.3.tar.xz
	cd revelation-0.5.3

Configure, make & install:

    # compile
    ./configure --prefix=$HOME./local
    make

    # install
    make install

    # run
    revelation ($HOME/.local/bin/revelation)

**Comment by silene** [comment]
I just tried these instructions. Overall, they work well, thanks a lot. Here are a few comments:
- Package `python3-cryptodome` does not exist, but `python3-pycryptodome` does.
- There is a typo on the `configure` line; it should read `./configure --prefix=$HOME/.local`.
- Installation fails too early when run as a non-root user; using `make -k install` was sufficient to get a working installation.

**Comment by mikelolasagasti** [comment]
> I just tried these instructions. Overall, they work well, thanks a lot. Here are a few comments:

Thanks for the feedback! I modified my comment with corrected steps.

**Comment by mikelolasagasti** [comment]
New steps to build described in README.md should avoid this issue.
