### ISSUE TITLE
Crash when right-click on entry details

### ISSUE THREAD

**Issue by janvrany** [mikelolasagasti/revelation#33]
I have installed Revelation commit 3f5813a7dbc3 into a custom prefix (see #29, just for clarity, I do not think custom prefix is problem here). 

When I select an entry in the list, I see details on right-hand pane (name, username and so on). When I right-click in this pane
to get a context menu on the entry, Revelation crashes, showing following in a crash dialog: 
```
Traceback (most recent call last):
  File "/opt/revelation/lib/python3.8/site-packages/revelation/ui.py", line 533, in __cb_button_press
    menu.popup(None, None, None, data.button, data.time)
TypeError: popup() missing 1 required positional argument: 'activate_time'
```

**Comment by mikelolasagasti** [comment]
@janvrany I'm not able to reproduce it building from master and installing it in `--prefix=/usr/local` (default location).
