### ISSUE TITLE
Improper escape on saving of auto startup filename

### ISSUE THREAD

**Issue by Heebron** [mikelolasagasti/revelation#6]
Select a file that has a space anywhere in the file path then set revelation to auto load that file. On startup, revelation will fail to open the file because it has turned the space into a %20 and does not tun it back into a space prior to trying to opening the file.

The work around is to use gconfeditor to manually turn the %20 into a space under the 
```
/apps/revelation/file/autoload_file
````
entry

**Comment by mikelolasagasti** [comment]
Fixed in `devel` branch.
