### ISSUE TITLE
Can not select text in search input

### ISSUE THREAD

**Issue by HumanG33k** [mikelolasagasti/revelation#73]
## Overview
Ctrl+A not select text in search input.

## Steps to Reproduce
1. Start  revelation 
2. Open a file containing entries
3. Open the search bar
4. Enter a search text 
5. Use Ctrl+A in order to select text 
6. Password entries are selected instead of search input containt   

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
1. Start  revelation 
2. Open a file containing entries
3. Open the search bar
4. Enter a search text 
5. Use Ctrl+A in order to select text 
6. All text in search input is select 

## Actual Behavior
Password entries are selected instead of search input containt

## Context

Revelation - 0.5.4-2

[NOTE]: # ( Pick choices based on your environment )
Operating System: Debian (testing)
Desktop Env: I3
Windowing System: X11

**Comment by gbm19** [comment]
You can use Control+F to select the text in search entry.

**Comment by HumanG33k** [comment]
ok i remember that.

Where this shortcut come from ? First time i meet it.

**Comment by gbm19** [comment]
Most shortcuts in revelation are defined in file `data/ui/menubar.ui`.  
Ctrl+F is set at line 149.

**Comment by HumanG33k** [comment]
i want to says what standard/normalisation/iso.

**Comment by mikelolasagasti** [comment]
Other apps have the same behavior. Tested with Firefox, Gedit and Chromium.

**Comment by HumanG33k** [comment]
@mikelolasagasti what behavior are you talking about ? 

I talking about Ctrl +a in Find form. 

Ctrl + a in Firefox/Chromium search do NOT select all html page  content.

**Comment by gbm19** [comment]
See  Standard application shortcuts/Edit in "Keyboard input" :[https://developer.gnome.org/hig/stable/keyboard-input.html.en](https://developer.gnome.org/hig/stable/keyboard-input.html.en)
Both Ctrl+A and Ctrl+F are defined there.

**Comment by HumanG33k** [comment]
I update the link https://developer.gnome.org/hig/reference/keyboard.html 
Which says the same thing as i already said. For me it's always a bug because : Selects all content in the focused control or view. the focus control is the search/filtered form.
