### ISSUE TITLE
can't build with meson

### ISSUE THREAD

**Issue by tpapp** [mikelolasagasti/revelation#79]
Following `README.md` on `master`, I tried to build, getting
```bash
~/src/revelation$ meson configure --prefix=$HOME/install _build
Meson configurator encountered an error:

ERROR: Directory /home/tamas/src/revelation/_build is neither a Meson build directory nor a project source directory.
```

Revelation - `master`
Revision: e19552d

Operating System: Ubuntu 20.10
Desktop Env: XFCE
Windowing System: X11

**Comment by DarianAnjuhal** [comment]
I had the same issue. So I used autotools compilation from the tag revelation-0.5.4.

**Comment by mikelolasagasti** [comment]
Try with `meson setup --prefix=$HOME/install _build` or even `meson --prefix=$HOME/install _build`. I'll change the step in the readme file.

**Comment by mikelolasagasti** [comment]
This two steps would be enough:

```
$ meson setup --prefix=$HOME/install _build
$ meson install -C _build
```
